// Error Handling the  in the js
// try {
//     console.log("try block start ");
//     //Referece block
//     console.log(x);
//     console.log("try block end here ");
// }
//       //Catch the error : X is not define
// catch (error){
//     console.log("I Am Inside catch ");
//     console.log("Print the error", error);
// }
// finally {
//     console.log("I will print the final  ");
// }



//      //coustom error
// try {
//       //Reference Error 
//     console.log(x)
// }
// catch(error){
//     throw new Error("Phala error declare kero ", "fir Print kero")
// }
// finally{
//     console.log("there is no error ");
// }




